sudo: required
services:
        - docker

before_install:
        - docker build -t joshmay2005/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true joshmay2005/docker-react npm run test
